deployment_rules:
  min_staging_duration_hours: 24
  require_a_b_testing: true
  require_staging_approval: true
  rollback_on_performance_degradation: true
monitoring:
  alert_on_threshold_breach: true
  drift_detection_threshold: 0.1
  performance_check_interval_minutes: 15
performance_thresholds:
  max_latency_p95: 20.0
  min_accuracy: 0.85
  min_adversarial_robustness: 0.7
  min_f1_score: 0.8
  min_precision: 0.8
  min_recall: 0.85
  min_throughput: 100.0
